// Code generated by Wire. DO NOT EDIT.

//go:generate go run gortc.io/wire/cmd/wire
//+build !wireinject

package main

import (
	"io"
	"strings"
)

// Injectors from wire.go:

func injectedReader() io.Reader {
	reader := _wireReaderValue
	return reader
}

var (
	_wireReaderValue = strings.NewReader("hello world")
)
